---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify | check restic binary exists
      ansible.builtin.stat:
        path: /usr/local/bin/restic
      register: restic_bin
      failed_when: not restic_bin.stat.exists

    - name: Verify | check restic is executable
      ansible.builtin.command: /usr/local/bin/restic version
      register: restic_version
      changed_when: false
      failed_when: restic_version.rc != 0

    - name: Verify | check backup timer is enabled
      ansible.builtin.systemd:
        name: "backup-database.timer"
      register: backup_timer
      failed_when: backup_timer.status.UnitFileState != 'enabled'

    - name: Verify | check backup service unit exists
      ansible.builtin.stat:
        path: /etc/systemd/system/backup-database.service
      register: backup_service
      failed_when: not backup_service.stat.exists

    - name: Verify | check backup script exists
      ansible.builtin.stat:
        path: /opt/restic/script/backup-database.sh
      register: backup_script
      failed_when: not backup_script.stat.exists

    - name: Verify | check restic backend config exists
      ansible.builtin.stat:
        path: /etc/restic/restic.env
      register: backend_config
      failed_when: not backend_config.stat.exists
